### ISSUE TITLE
Taxon names matching to wrong Kingdom

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#10]
the placement of the other Accepted and Inferred Accepted names has used the ALA fuzzy matching and makes serious errors. Two more dreadful examples, both of molluscs (reported with animal classifications in CAAB) that have been grafted into Plantae e.g Mitrella dictua and Ficus. This means that, even when the ALA reports no fuzzy matching issues, fuzzy matching has occurred and degraded data.

**Comment by charvolant** [comment]
20230329-1 index

*  Mitrella dictua is no longer in the index after CAAB reworking.
* Ficus generates a homonym exception
  *  Ficus with a kingdom of Plantae matches to https://id.biodiversity.org.au/taxon/apni/51439476
  *  Ficus with a kingdom of Animalia matches to https://biodiversity.org.au/afd/taxa/3b379a3e-4407-4a4f-988d-f1b49e7d98e0

**Comment by CamSlatyer** [comment]
Fixed in tactical taxonomy
