### ISSUE TITLE
Phrase name listed species missing Paranotis sp. Pilbara (H. Ajduk HAOP04a) PN

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#100]
WA phrase name missing from threatened species list

**Comment by charvolant** [comment]
20230329-1 index

* Paranotis sp. Pilbara (H. Ajduk HAOP04a) matches https://id.biodiversity.org.au/name/apni/51680203 (APNI only)

**Comment by CamSlatyer** [comment]
Duplication removed - now correct in tactical taxonomy
