### ISSUE TITLE
Missing listed phrase name taxa Stackhousia muricata subsp. Perennial (W.R. Barker 3641) PN and Stenanthemum sp. Eganu (S. Patrick 4537) PN

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#103]
WA listed species missing Stackhousia muricata subsp. Perennial (W.R. Barker 3641) PN and Stenanthemum sp. Eganu (S. Patrick 4537) PN

**Comment by charvolant** [comment]
20230329-2 index

Multiple instances of Stackhousia muricata subsp. Perennial 

* https://id.biodiversity.org.au/name/apni/51381633 Stackhousia muricata subsp. "Perennial" (W.R.Barker 3641)
* https://id.biodiversity.org.au/node/apni/2893055 Stackhousia muricata subsp. Perennial (W.R.Barker 3641)
* ALA_DR467_3219 Stackhousia muricata subsp. Perennial (W.R. Barker 3641) PN https://lists.ala.org.au/speciesListItem/list/dr467?q=Stackhousia+muricata+subsp.+Perennial+%28W.R.+Barker+3641%29+PN

See https://github.com/AtlasOfLivingAustralia/ala-name-matching/issues/201

* Stenanthemum sp. Eganu (S. Patrick 4537) matches https://id.biodiversity.org.au/name/apni/51680215 (APNI only)

**Comment by Sherrin-ALA** [comment]
Note that the multiple Stackhousia need to be referred to APNI.

**Comment by CamSlatyer** [comment]
In new taxonomy but null error presents

**Comment by CamSlatyer** [comment]
Duplication removed, correct in new taxonomy
