### ISSUE TITLE
Missing listed phrase name taxa Streptoglossa sp. South Coast (R.M. Hoggart 16/1113) PN

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#104]
WA listed phrase name missing Streptoglossa sp. South Coast (R.M. Hoggart 16/1113) PN

**Comment by charvolant** [comment]
20230329-2 index

* Streptoglossa sp. South Coast (R.M. Hoggart 16/1113) matches https://id.biodiversity.org.au/name/apni/51680218 (APNI only)

**Comment by CamSlatyer** [comment]
In new taxonomy but duplicated between APNI and threatened species lists

**Comment by CamSlatyer** [comment]
Duplication now corrected in tactical taxonomy
