### ISSUE TITLE
New listed species missing Styphelia blackallii, Styphelia carolineae, Styphelia caudata, Styphelia exarata, Styphelia graniticola, Styphelia intricata and Styphelia undulata

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#105]
WA listed species  - new species missing  - Styphelia blackallii, Styphelia carolineae, Styphelia caudata, Styphelia exarata, Styphelia graniticola, and Styphelia intricata  (Nuytsia 33:213-215, (2022))

**Comment by charvolant** [comment]
20230329-2 index

* Styphelia blackallii matches https://id.biodiversity.org.au/name/apni/51694043 (APNI only)
* Styphelia carolineae matches https://id.biodiversity.org.au/name/apni/51631427 (APNI only)
* Styphelia caudata matches https://id.biodiversity.org.au/name/apni/51631355 (APNI only)
* Styphelia exarata matches https://id.biodiversity.org.au/name/apni/51631432 (APNI only)
* Styphelia graniticola matches https://id.biodiversity.org.au/name/apni/51631398 (APNI only)
* Styphelia intricata matches https://id.biodiversity.org.au/name/apni/51631410 (APNI only)
* Styphelia undulata matches https://id.biodiversity.org.au/name/apni/51424442 (APNI only)

**Comment by CamSlatyer** [comment]
In new taxonomy but null value presents

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
