### ISSUE TITLE
Missing listed phrase name species Styphelia sp. Watheroo (M. Hislop 4324) PN

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#106]
WA missing phrase name species that are listed -  Styphelia sp. Watheroo (M. Hislop 4324) PN

**Comment by charvolant** [comment]
20230329-2 index

* Styphelia sp. Watheroo (M. Hislop 4324) matched to ALA_DR467_3384 https://lists.ala.org.au/speciesListItem/list/dr467?q=Styphelia+sp.+Watheroo+%28M.+Hislop+4324%29+PN

**Comment by Sherrin-ALA** [comment]
Not seeing this in the current development build - will investigate

**Comment by Sherrin-ALA** [comment]
Is there now.

**Comment by CamSlatyer** [comment]
In taxonomy but null value error presents and species is duplicated between conservation list and APNI

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
