### ISSUE TITLE
New listed species (2022) Swainsona picta

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#107]
New listed species for WA not in ALA - Swainsona picta - Swainsona picta R.W.Davis & T.Hammer
Swainsona 36:71-73, Fig. 1 (2022)

**Comment by Sherrin-ALA** [comment]
In current dev build of taxon - sourced from APNI

**Comment by CamSlatyer** [comment]
In taxonomy but null error presents

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
