### ISSUE TITLE
New listed species (2022) Synostemon arenosus

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#108]
New listed species in WA -  Synostemon arenosus - Synostemon arenosus (J.T.Hunter & J.J.Bruhl) I.Telford & J.J.Bruhl
Phytotaxa 540(1):67 (2022)

**Comment by charvolant** [comment]
20230229-2 index

* Synostemon arenosus matches to https://id.biodiversity.org.au/name/apni/51681588 (APNI only)

**Comment by CamSlatyer** [comment]
Correctly in tactical taxonomy as an synonym of APC name [Sauropus arenosus J.T.Hunter & J.J.Bruhl](https://id.biodiversity.org.au/name/apni/170688/api/apni-format)
