### ISSUE TITLE
Missing Listed phrase name Themeda sp. Panorama (J. Nelson et al. NS 102) PN

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#109]
WA missing listed phrase name Themeda sp. Panorama (J. Nelson et al. NS 102) PN

**Comment by charvolant** [comment]
20230329-2 index

* Themeda sp. Panorama (J. Nelson et al. NS 102) matched to ALA_DR467_3537 https://lists.ala.org.au/speciesListItem/list/dr467?q=Themeda+sp.+Panorama+%28J.+Nelson+et+al.+NS+102%29+PN

**Comment by Sherrin-ALA** [comment]
Missing from current dev index - will investigate.

**Comment by Sherrin-ALA** [comment]
There now.

**Comment by CamSlatyer** [comment]
In tactical taxonomy
