### ISSUE TITLE
New missing listed taxa - Utricularia baliboongarnang

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#110]
WA new listed species Utricularia baliboongarnang - Utricularia baliboongarnang Baleeiro & R.W.Jobson
Telopea 25:68-72, Figs 4, 6 (2022)

**Comment by charvolant** [comment]
20230329-2 index

* Utricularia baliboongarnang matched https://id.biodiversity.org.au/name/apni/51680807 (APNI only)

**Comment by CamSlatyer** [comment]
Species in new taxonomy but null error presents

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
