### ISSUE TITLE
Incorrect junior synonym applied as spelling error Eriachne armittii F.Muell. ex Benth should be spelt Eriachne armitii F.Muell. ex Benth

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#112]
Eriachne armitii F.Muell. ex Benth. only has one "t" - this error is present in ALA and not APC/APNI. Eriachne armittii is listed as an incoorect orthographic variant: [Eriachne armittii Benth.](https://id.biodiversity.org.au/name/apni/234152/api/apni-format)  orth. var.

**Comment by charvolant** [comment]
20230329-2 index

* Eriachne armittii matches https://id.biodiversity.org.au/instance/apni/916406 which has acceped https://id.biodiversity.org.au/node/apni/2892656 Eriachne armitii

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
