### ISSUE TITLE
Incorrect junior synonym Pyrrholaemus sagittatus (Latham, 1801) (in AFD) referred to as Pyrrholaemus sagittata (Latham, 1801) in AFD

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#113]
The loading of names from AFD and APNI appear to, on occasion, introduce an error by applying a junior species epithet. In this instance, Pyrrholaemus sagittatus (Latham, 1801) is correctly referred to in AFD, but it has been loaded into ALA as Pyrrholaemus sagittata (Latham, 1801). There is a junior synonym of [Pyrrholaemus sagittata (Latham, 1801)](https://biodiversity.org.au/afd/taxa/Pyrrholaemus_sagittata) listed in ALA as an alternative generic combination wihich ALA has used.

**Comment by TaniaGLaity** [comment]
agreed - could combine

**Comment by charvolant** [comment]
See #127

**Comment by Sherrin-ALA** [comment]
P.sagittata is now listed as a synonym of P.sagittatus in current development build

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
