### ISSUE TITLE
Junior nomenclatural synonym -  Genoplesium sp. Densum (M.A.Clements 1748) should be Corunastylis densa (Fitzg.) D.L.Jones & M.A.Clem. 

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#117]
One of a large number of errors where our names loading has appeared to randomly have taken a junior synonym as the correct name instead of the APC selected name. Genoplesium sp. Densum (M.A.Clements 1748) should be Corunastylis densa (Fitzg.) D.L.Jones & M.A.Clem. (synonym in ALA)

**Comment by charvolant** [comment]
2023029-2 index

* Genoplesium sp. Densum (M.A.Clements 1748) matches https://id.biodiversity.org.au/instance/apni/51441084 with accepted taxon https://id.biodiversity.org.au/taxon/apni/51441090 - Corunastylis densa

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
