### ISSUE TITLE
Name matching error. Galaxias Sp 14 incorrectly matches to Galaxias terenasus instead of Galaxias gunaikurnai Raadik, 2014 (AFD)

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#120]
Wrong species - Galaxias Sp 14 is listed in AFD as a nomenclatural synonym of Galaxias gunaikurnai Raadik, 2014. ALA correctly reflects this but incorrectly matches sp 14 to a sister taxon G. terenasus when loading lists. Correctly goes to G. gunaikurnai when the front page query is used.

**Comment by charvolant** [comment]
20230329-2 index 

* Galaxias Sp 14 by itself generates a homonym error with a single result, canonical match to https://biodiversity.org.au/afd/taxa/cf9d20e7-5234-4ff3-94a2-23802357365f
* Galaxias sp. 14 does not match, since the name came from CAAB

**Comment by Sherrin-ALA** [comment]
Galaxias sp 14 was not included in AFD export. ABRS have been informed.

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
