### ISSUE TITLE
Junior nomenclatural synonym shown as senior - Machaerina laxa (Nees) T.Koyama is the correct current name for Baumea laxa (Nees) Boeckeler

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#122]
One of a large number of errors where our names loading has appeared to randomly have taken a junior synonym as the correct name instead of the APC selected name. Nomenclatural synonym - Machaerina laxa (Nees) T.Koyama is the correct current name for Baumea laxa (Nees) Boeckeler

**Comment by charvolant** [comment]
20230329-1 index

* Machaerina laxa matches https://id.biodiversity.org.au/taxon/apni/51434593
* Baumea laxa matches https://id.biodiversity.org.au/instance/apni/51434588 with an accepted taxon of https://id.biodiversity.org.au/taxon/apni/51434593

**Comment by CamSlatyer** [comment]
Correct in new taxonomy but null value presents

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
