### ISSUE TITLE
Threatened species - localised epiphet has dropped off - the listed species is Pseudemoia pagenstecheri (High Country) not Pseudemoia  pagenstecheri (which is widespread). The species needs to be added to ALA

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#125]
Localised epiphet has dropped off - the listed species is Pseudemoia pagenstecheri (High Country) not Pseudemoia  pagenstecheri (which is widespread). The species needs to be added to ALA. When matching the threatened species list, the matching simply took off the () and matched to species. This is a potential major error for data matching

**Comment by charvolant** [comment]
20230329-1 index

https://lists.ala.org.au/speciesListItem/list/dr655?q=Pseudemoia++pagenstecheri+%28High+Country%29 is being reallocated to https://biodiversity.org.au/afd/taxa/b1bad487-2f7c-41fe-9216-96cfe25bfc78 by the LTC

Before turning this into an issue for ala-name-matching I need to get a sense of what the difference is between Pseudemoia pagenstecheri (High Country) and Pseudemoia pagenstecheri. Is it the same species but with the sensitivity localised to the high country or a separate species? See #4

**Comment by Sherrin-ALA** [comment]
This is a geographic issue - solved as part of the issue with Bettongia lesueur

**Comment by CamSlatyer** [comment]
_Taxon placed in tactical taxonomy
