### ISSUE TITLE
Wrong species - Pterostylis sp. aff. plumosa (Anglesea) and Pterostylis sp. Anglesea (V.Stajsic 355) should both match to Pterostylis unicornis (D.L.Jones) D.L.Jones

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#126]
Wrong species - Pterostylis sp. aff. plumosa (Anglesea) and Pterostylis sp. Anglesea (V.Stajsic 355) should both match to Pterostylis unicornis (D.L.Jones) D.L.Jones

**Comment by charvolant** [comment]
20230329-1 index

* Pterostylis sp. aff. plumosa (Anglesea) matches https://id.biodiversity.org.au/instance/apni/51441985 with an accepted taxon of https://id.biodiversity.org.au/taxon/apni/51441988 - P. unicornis
* Pterostylis sp. Anglesea (V.Stajsic 355) matches https://id.biodiversity.org.au/instance/apni/51441984 also with an accepted taxon of https://id.biodiversity.org.au/taxon/apni/51441988

**Comment by CamSlatyer** [comment]
Taxonomy correct but showing null value error

**Comment by CamSlatyer** [comment]
Correctly resolved in tactical taxonomy
