### ISSUE TITLE
Junior synonym incorrectly shown: Pyrrholaemus sagittata (Latham, 1801) instead of Pyrrholaemus sagittatus (Latham, 1801)

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#127]
AFD shows Pyrrholaemus sagittatus (Latham, 1801) as the current correct name with Pyrrholaemus sagittata (Latham, 1801) as a junior alternative generic combination. ALA is incorrectly showing the junior combination. One of a large number of errors where our names loading has appeared to randomly have taken a junior synonym as the correct name instead of the preferred name in either AFD or APC.

**Comment by Sherrin-ALA** [comment]
This appears to be a duplication of issue #113 https://github.com/AtlasOfLivingAustralia/Taxonomic-Issues-Register_new/issues/113

**Comment by CamSlatyer** [comment]
Hi Simon

There are a number of duplications. The reason for including duplications was so that they weren’t dealt with as single issues related to a single taxon but as a class of issues.

Best wishes
Cam

**Comment by charvolant** [comment]
20230329-1 index

* Pyrrholaemus sagittata matches to https://biodiversity.org.au/afd/taxa/29ef1670-1ccf-4186-a58d-637a6559610 with accepted taxon https://biodiversity.org.au/afd/taxa/924778ad-245b-400f-a497-af8700c22674 - P. sagittatus
* Pyrrholaemus sagittatus matches to https://biodiversity.org.au/afd/taxa/924778ad-245b-400f-a497-af8700c22674

**Comment by CamSlatyer** [comment]
Resolved in new taxonomy - APNI refers to Pyrrholaemus sagittatus
