### ISSUE TITLE
Threatened species - localised epiphet has dropped off - the listed species is Rankinia diemensis (Grampians) not Rankinia diemensis (which is widespread). The species needs to be added to ALA

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#128]
Threatened species - localised epiphet has dropped off - the listed species is Rankinia diemensis (Grampians) not Rankinia diemensis (which is widespread). The species needs to be added to ALA. When matching the threatened species list, the matching simply took off the () and matched to species. This is a potential major error for data matching

**Comment by charvolant** [comment]
See #125 and #4

**Comment by Sherrin-ALA** [comment]
Same as #125 - will be dealt with as part of the general solution to this issue.

**Comment by CamSlatyer** [comment]
Correctly added to tactical taxonomy
