### ISSUE TITLE
Hydrochus genus appearing within family Hydophilidae - should be in Family Hydrochidae

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#130]
Hydrochus genus appearing within family Hydophilidae - should be in Family Hydrochidae according to AFD

**Comment by charvolant** [comment]
20230329-1 index

Hydrochus generates a homonym exception.

The IRMNG dataset that has two entries for Hydrochus

```csv
kingdom,phylum,class,order,family,genus
Animalia,Arthropoda,Insecta,Coleoptera,Hydrophilidae,Hydrochus
Animalia,Arthropoda,Insecta,Diptera,Diptera (awaiting allocation),Hydrochus
```

The name index build also seems to be putting  the kingdom where the family should be. See https://github.com/AtlasOfLivingAustralia/ala-name-matching/issues/198

**Comment by Sherrin-ALA** [comment]
Current dev index puts  Hydrochus in the family Hydrochidae

**Comment by CamSlatyer** [comment]
Corrected in tactical taxonomy
