### ISSUE TITLE
Species in hares (Lepus) and species pages are incorrect

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#131]
Lepus has one known species in Australia, Lepus capensis orientalis (using AFD as the authority). The ALA has two species, L. c. orientalis (derived from AFD) and L. europaeus orientalis (a synonym of L. capensis)  (derived from NZOR). Unfortunately the species page descriptions are also incorrect. The description for L. e. orientalis is the correct description for Australia. The species page for L. c. orientalis appears to be using the EoL page for L. c. arabica.

**Comment by charvolant** [comment]
202303290-1 index

The following taxa are listed:

* Lepus capensis https://biodiversity.org.au/afd/taxa/6240deca-2f4f-4bcd-a944-c49df0ae83b5
* Lepus capensis occidentalis https://biodiversity.org.au/afd/taxa/c521424d-2add-47a9-98b2-a4de4affe739
* NZOR-6-55337 Lepus europaeus
* https://biodiversity.org.au/afd/taxa/c14a6934-5603-4bdd-aef8-ccb48df8bd8e Lepus europaeus synonym of https://biodiversity.org.au/afd/taxa/6240deca-2f4f-4bcd-a944-c49df0ae83b5
* https://biodiversity.org.au/afd/taxa/ab2ce457-c400-44e2-86cf-108d10f425d7 Lepus europaeus occidentalis Winton, 1898 synonym of https://biodiversity.org.au/afd/taxa/c521424d-2add-47a9-98b2-a4de4affe739
* NZOR-6-52652 Lepus europaeus occidentalis	de Winton

The duff authorship in NZOR is a product of misinterpreting the NZOR data. See https://github.com/AtlasOfLivingAustralia/name-preprocessing/issues/9

**Comment by Sherrin-ALA** [comment]
Species page no longer appears to include EoL info -  Lepus capensis occidentalis is in ALA  not orientalis

**Comment by CamSlatyer** [comment]
Corrected in tactical taxonomy
