### ISSUE TITLE
Misplacement of Codium (algae) in ALA taxonomic tree 

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#132]
There are currently two placements of the genus Codium in the ALA one (derived from NZOR) is correctly kingdom (Plantae), subkingdom (Viridiplantae), infrakingdom (Chlorophyta), phylum (Chlorophyta), class (Chlorophyceae), order (Codiales), family (Codiaceae), genus (Codium). However the genus has also been incorrectly placed within the wasp genus [Chetogaster Macquart, 1851](https://biodiversity.org.au/afd/taxa/Chetogaster) - Chetogaster is correctly placed within the ALA taxonomy but has a number of Codium genus/species combinations (both valid and unranked) placed against it, most names coming from CAAB. The Chetogaster (Codium) taxonomy needs to be removed and relevant records referred to Codium.

**Comment by charvolant** [comment]
20230329-2 index

* Combined taxonomy has
  * Codium NZOR-6-62176 http://data.nzor.org.nz/names/884a78bd-7f72-40f8-b65e-d7bb0d70a76c with higher taxonomy Codiaceae > Codiales > Chlorophyceae > Chlorophyta (phylum) > Chlorophyta (infrakingdom) > Viridiplantae > Plantae (all NZOR except Plantae)
  * Codium https://biodiversity.org.au/afd/taxa/ff8b3656-55de-4146-be42-27904d5fbe85 synonym of  https://biodiversity.org.au/afd/taxa/bd273b8b-4752-4f56-874c-a2250d53a4e2 Chetogaster (Insecta)
  * All Codium species 
* Codium generates a homonym exception
  * First result is https://biodiversity.org.au/afd/taxa/ff8b3656-55de-4146-be42-27904d5fbe85
  * Second result is NZOR-6-62176
* Codium with kingdom Plantae returns NZOR-6-62176 and familty Codiaceae
* Codium species all have  NZOR-6-62176 as a parent eg Codium bursa NZOR-6-19985

**Comment by Sherrin-ALA** [comment]
In the current dev build of the taxon - there are no species under Chetogaster.

**Comment by CamSlatyer** [comment]
Corrected in new taxonomy
