### ISSUE TITLE
Nimbosocus - Myopsocus - failure to synonymise in Pyscoptera

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#133]
AFD has 
Nimbopsocus australis: 
https://biodiversity.org.au/afd/taxa/Nimbopsocus_australis  and

Myopsocus australis: 
https://biodiversity.org.au/afd/taxa/Myopsocus_australis;Myopsocus
The Atlas of Living Australia also has entries under both names:

[https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/ee555f1e-b0ae-4df3-92f0-f98d2fa762dd](https://bie.ala.org.au/species/https:/biodiversity.org.au/afd/taxa/ee555f1e-b0ae-4df3-92f0-f98d2fa762dd)

[https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/345ac449-ad4d-485c-acdf-d042d117f390](https://bie.ala.org.au/species/https:/biodiversity.org.au/afd/taxa/345ac449-ad4d-485c-acdf-d042d117f390)

The 2nd of these Myopsocus australis includes the statement:

> In 2004, the valid name for Myopsocus australis became Nimbopsocus 
> australis. This name change stands undisputed. For more details, see 
> Wikispecies: https://species.wikimedia.org/wiki/Nimbopsocus_australis
It seems to me probable that both AFD and ALA should merge the two 
species under the name: Nimbopsocus australis

**Comment by charvolant** [comment]
20230329-2 index

* Nimbopsocus australis matches https://biodiversity.org.au/afd/taxa/ee555f1e-b0ae-4df3-92f0-f98d2fa762dd - Nimbopsocus australis (accepted)
* Myopsocus australis matches https://biodiversity.org.au/afd/taxa/345ac449-ad4d-485c-acdf-d042d117f390 - Myopsocus australis (accepted)
* A recent change to AFD  has replaced M. australias with https://biodiversity.org.au/afd/taxa/732b2ee3-4bc3-47b2-bda7-ef9bec49fb27 which is N. australis. 
 
 This should be caught in the next refresh from AFD

**Comment by CamSlatyer** [comment]
Corrected
