### ISSUE TITLE
Senior synonym Phragmites karka incorrectly referred to invalid junior synonym P. vallatorius

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#142]
a) Phragmites vallatorius is a nom illeg (basically an illegal name). It was previously designated as such before 2021  but was re listed as nom illegal by APC 2021 and assigned to P. karka. Here is the weird bit. Our instance in prod of Phragmites vallatorius shows it as nom illegal (https://bie.ala.org.au/species/https:/id.biodiversity.org.au/node/apni/2888352#namesbut) still shows it as the preferred name. I’ve checked but in dev it is also showing as accepted, even though APC aren’t accepting it (noting that it is a pre 2021 issue).

b) The second bit might be slightly less odd but still an error. In APC, Phragmites karka (Retz.) Trin. ex Steud. var. karka is an excluded name but Phragmites karka (Retz.) Trin. ex Steud. is an accepted name under APC https://biodiversity.org.au/nsl/services/rest/name/apni/84600/api/apni-format as well as the name to which P. vallatorius has been referred. Again, this happened in 2021, but before then there was still a problem. P. karka was a valid taxon even without APC and P. vallatorius was never a valid taxa. I think when we are importing the names, the system is conflating the two instances of P. karka and then referring everything to P. vallatorius….

**Comment by Sherrin-ALA** [comment]
As I understand the above - both _Phragmites vallatorius_ and  _Phragmites karka_ (Retz.) Trin. ex Steud. var. karka should be redirected to _Phragmites karka_ (Retz.) Trin. ex Steud.

In dev - _Phragmites vallatorius_ redirects   _Phragmites karka_ (Retz.) Trin. ex Steud., but _Phragmites karka_ (Retz.) Trin. ex Steud. var. karka doesn't as in the APC taxon file, it's listed as an excluded name but references itself as the accepted name with its parent name as Poaceae (the same family as _Phragmites karka_ (Retz.) Trin. ex Steud.
