### ISSUE TITLE
Exclude Commercial Names, Section Botany, and Subsection Botany from APC/APNI

### ISSUE THREAD

**Issue by Sherrin-ALA** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#145]
Exclude commercial cultivars, and entries with rank Section Botany and Subsection Botany from APC/ANPI taxonomy

**Comment by Sherrin-ALA** [comment]
Commercial Cultivars are coming through with a rank of "unknown"
Section Botany has a rank of "section botany"
Subsection Botany has a rank of "subsection botany"

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
