### ISSUE TITLE
Thinornis rubricollis to be made synonym of Thinornis cucullatus (Vieillot, 1818)

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#15]
Thinornis rubricollis to be made synonym of Thinornis cucullatus (Vieillot, 1818). Currently Thinornis rubricollis is an unranked taxon under genus in ALA.  On SA sensitive species list

**Comment by charvolant** [comment]
20230329-1 index

Uses of T. rubricollis:

* Thinornis rubricollis rubricollis https://lists.ala.org.au/speciesListItem/list/dr654?q=Thinornis+rubricollis+rubricollis+ inferred uplaced
* Thinornis rubricollis tregellasi https://biodiversity.org.au/afd/taxa/ef1d8551-f5b4-4830-ab1c-858a48f59f0c synonymised to Thinornis cucullatus tregellasi https://biodiversity.org.au/afd/taxa/ef1d8551-f5b4-4830-ab1c-858a48f59f0c as misc. literature

Proposed corrections in dr7933:

* Synonymise  Thinornis rubricollis rubricollis to Thinornis cucullatus (cucullatus?) as misc. literature
* Synonymise Thinornis rubricollis to Thinornis cucullatus https://biodiversity.org.au/afd/taxa/1ebf8ec6-9aee-4b58-8789-0be73eb97b2f as misc. literature.

**Comment by Sherrin-ALA** [comment]
Thinornis rubicollis not synonymised in AFD. Cam to ask AFD to correct, rather than adding to dr7933

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
