### ISSUE TITLE
Species Page issues - Homonym - Stenella

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#155]
Stenella is a Dolphin https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/0b266f52-0cdc-400e-bda2-98f14c33e32d and a fungi https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/fungi/60081845  . All data etc seems to be OK but the description in the dolphin is for the fungi

**Comment by Sherrin-ALA** [comment]
Will get Stenella added to the black list for bie-hub - have created an issue in bie-hub repo -https://github.com/AtlasOfLivingAustralia/ala-bie-hub/issues/66

**Comment by Sherrin-ALA** [comment]
Added to the blacklist by Adam Collins - closed -https://github.com/AtlasOfLivingAustralia/ala-bie-hub/issues/66

**Comment by CamSlatyer** [comment]
Have used Adam's tool to reference the correct wikipedia pages
