### ISSUE TITLE
Morelia duplicate species names

### ISSUE THREAD

**Issue by Sherrin-ALA** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#156]
From the following ticket -https://support.ehelp.edu.au/helpdesk/tickets/182837
"Furthermore, you have a couple of infraspecific names (spilota and metcalfei) listed twice, one record appropriately placed in the hierarchy and a duplicate at species level."

**Comment by CamSlatyer** [comment]
Fixed in tactical taxonomy
