### ISSUE TITLE
Leioproctus zephyr and other re-arrangements

### ISSUE THREAD

**Issue by Sherrin-ALA** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#157]
Ken Walker updated the taxonomy of several bee groups, including the addition of Leioproctus zephyr, however these weren't in the initial update from AFD. Check for:
Leioproctus zephyr
Colletidae subfamilies: Callomelittinae, Diphaglossinae, Neopasiphaeinae
Halictinae genera: Homalictus reallocated to Lasioglossum

**Comment by CamSlatyer** [comment]
Issue rectified in tactical taxonomy
