### ISSUE TITLE
Theridiidae Nihonhimea mundula missing from index 

### ISSUE THREAD

**Issue by Sherrin-ALA** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#158]
From https://support.ehelp.edu.au/a/tickets/152923

"The spider species Nihonhimea mundula (previously in Parasteatoda and previous to that, Achaearanea) seems to have gone missing. Our Museum factsheet previously had a link to an ALA map using one of those earlier names but it is no longer working."

**Comment by CamSlatyer** [comment]
Not in AFD and not in any spider catalogues I can access - Have passed on to ABRS

**Comment by CamSlatyer** [comment]
Corrected in tactical taxonomy
