### ISSUE TITLE
Reverse synonym (APNI to APC) not working in Tactical Taxonomy - Astroloma sp. Dumbleyung (A.J.G.Wilson 146)

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#169]
Retain as an example to test:
Astroloma sp. Kalbarri (D. & B.Bellairs 1368) is APC accepted, but was redescribed in 2019 as Styphelia cernua. Tactical taxonomy is failing to make the link between the two taxa (link is made in the conservation list, but presumably gets taken out in refinement process).  Presumably an issue with APNI and APC files - but a useful test for future.

**Comment by Sherrin-ALA** [comment]
Something is happening to the link in the merge process. The link between Astroloma sp. Kalbarri and Styphelia cernua is still in the refined conservation list - https://lists.ala.org.au/speciesListItem/list/dr22912?q=Astroloma+sp.+Kalbarri+ and should be there as part of the input into the merge process. Will need to investigate why the link is dropped - quick assumption is that the APC accepted entry is over-ruling the synonym entry from conservation.

**Comment by Sherrin-ALA** [comment]
Update: The correction to the APNI file now has Styphelia cernua being marked as a synonym of Astroloma sp. Kalbarri
