### ISSUE TITLE
Reverse synonym (APNI to APC) not working in Tactical Taxonomy - Baeckea sp. Baladjie (P.J.Spencer 24) WA Herbarium

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#170]
Retain as an example to test:
Baeckea sp. Baladjie (P.J.Spencer 24) WA Herbarium is APC accepted, but was redescribed in 2023 as Balaustion spenceri Rye(https://id.biodiversity.org.au/name/apni/51691650/api/apni-format). Tactical taxonomy is failing to make the link between the two taxa (link is made in the conservation list, but presumably gets taken out in refinement process). Presumably an issue with APNI and APC files - but a useful test for future.

**Comment by Sherrin-ALA** [comment]
Baeckea sp. Baladjie doesn't appear in either conservation list.
https://lists.ala.org.au/speciesListItem/list/dr23928?q=Baeckea+sp.+Baladjie
https://lists.ala.org.au/speciesListItem/list/dr23929?q=Baeckea+sp.+Baladjie

**Comment by Sherrin-ALA** [comment]
Update: The correction to the APNI file now has Balaustion spenceri as a synonym of Baeckea sp. Baladjie (P.J.Spencer 24) WA Herbarium. However, Balaustion spenceri also appears as an accepted name from the conservation list.

**Comment by CamSlatyer** [comment]
Yes, it does

***@***.***

**Comment by CamSlatyer** [comment]
Correctly referenced in tactical taxonomy
