### ISSUE TITLE
Petrogale lateralis subsp. (WAM M15135) - needs to be created as an unranked taxon

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#19]
Petrogale lateralis subsp. (WAM M15135) -  needs to be created as an unranked taxon under Petrogale lateralis as it is listed on WA sensitive species list - currently records assigned to genus

**Comment by charvolant** [comment]
20230329-1 index

Current WA list contains 

* Petrogale lateralis subsp. (MacDonnell Ranges)
* Petrogale lateralis hacketti
* Petrogale lateralis lateralis
* Petrogale lateralis subsp. (West Kimberley)

https://lists.ala.org.au/speciesListItem/list/dr2201?q=Petrogale+lateralis

WA sensitive list contains

* Petrogale lateralis centralis
* Petrogale lateralis hacketti
* Petrogale lateralis kimberleyensis
* Petrogale lateralis lateralis

https://lists.ala.org.au/speciesListItem/list/dr467?q=Petrogale+lateralis

No records with supplied name of `Petrogale lateralis subsp. (WAM M15135)`
https://biocache.ala.org.au/occurrences/search?q=raw_name%3A%22Petrogale+lateralis+subsp.+%28WAM+M15135%29%22
