### ISSUE TITLE
Correction synonomies in Erochilus

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#2]
ALA is not correctly representing APC taxonomy in Eriochilus. Eriochilus dilatatus subsp. brevifolius (Benth.) Hopper & A.P.Br. is the APC approved name for Eriochilus dilatatus subsp. undulatus. Eriochilus glareosus G.Brockman & C.J.French is the APC current name for Eriochilus sp. Roleystone (G. Brockman 1140). ALA currently refers Eriochilus sp. Roleystone (G. Brockman 1140) incorrectly to Eriochilus dilatatus subsp. undulatus. ALA does not have Eriochilus glareosus G.Brockman & C.J.French as a valid taxa and also shows both Eriochilus dilatatus subsp. undulatus and Eriochilus dilatatus subsp. brevifolius (Benth.) Hopper & A.P.Br as accepted taxa.

**Comment by charvolant** [comment]
20230329-1 matches for:

* Eriochilus dilatatus subsp. undulatus https://id.biodiversity.org.au/taxon/apni/51441698 - Eriochilus dilatatus subsp. undulatus Hopper & A.P.Br. 
* Eriochilus sp. Roleystone (G. Brockman 1140) https://id.biodiversity.org.au/taxon/apni/51441703 - Eriochilus sp. Roleystone (G.Brockman 1140)
* Eriochilus glareosus https://biodiversity.org.au/nsl/services/rest/name/apni/51694057 - Eriochilus glareosus G.Brockman & C.J.French 
* Eriochilus dilatatus subsp. brevifolius https://biodiversity.org.au/nsl/services/rest/taxon/apni/51405074 - Eriochilus dilatatus subsp. brevifolius (Benth.) Hopper & A.P.Br.

**Comment by charvolant** [comment]
Eriochilus glareosus is from APNI and does not seem to have yet been placed in APC. It is treated as inferred accepted until then.

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
