### ISSUE TITLE
Petrogale lateralis subsp. (ANWC CM15314) - needs to be created as an unranked taxon

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#20]
Petrogale lateralis subsp. (ANWC CM15314) - needs to be created as an unranked taxon under Petrogale lateralis as it is listed on WA sensitive species list - currently records assigned to genus

**Comment by charvolant** [comment]
See issue #19

**Comment by charvolant** [comment]
No records with provided name found in biocache https://biocache.ala.org.au/occurrences/search?q=raw_name%3A%22Petrogale+lateralis+subsp.+%28ANWC+CM15314%29%22

**Comment by Sherrin-ALA** [comment]
No longer on the sensitive species list.
