### ISSUE TITLE
Correction synonomies in Goodenia

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#3]
ALA is not correctly referencing synonymies in Goodenia. Goodenia pritzelii is on the WA sensitive species list. Goodenia pritzelii Domin is a valid taxa according to APC (2006). The ALA matches this taxon incorrectly to Goodenia microptera F.Muell., also a valid taxon according to APC 2007

**Comment by charvolant** [comment]
Tests using 20230329-1

* Goodenia pritzelii https://id.biodiversity.org.au/taxon/apni/51437035 - Goodenia pritzelii

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
