### ISSUE TITLE
Haitia acuta to be synonymised to Physa acuta

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#32]
Observations with the name Haitia acuta are currently attached to the familiy Physidae - they need to be synonymised to Physa acuta and observations updated to reflect this

**Comment by Sherrin-ALA** [comment]
Is there a source for the synonymy?

**Comment by Sherrin-ALA** [comment]
Cam will raise as an issue with ABRS

**Comment by CamSlatyer** [comment]
Corrected
