### ISSUE TITLE
Eria intermedia and Eria dischorensis should be synonyms of Bryobium dischorense

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#35]
Eria intermedia and Eria dischorensis should be synonyms of Bryobium dischorense according to APNI - listed on QLD sensitive species list. need to add Bryobium dischorense as accepted name on taxonomic backbone and change Eria intermedia and Eria dischorensis to synonyms of this.

**Comment by Sherrin-ALA** [comment]
Appears to be correctly synonymised in the 20230329 build - have written test case testIssue35 to confirm.

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
