### ISSUE TITLE
Canis lupus familaris should be a synonym of Canis familiaris

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#39]
Canis lupus familaris should be a synonym of Canis familiaris according to AFD.  there are two entries on the taxonomic backbone - they should be synonymised

**Comment by Sherrin-ALA** [comment]
_Canis lupus familiaris_ overriding the AFD synonym

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
