### ISSUE TITLE
Rhinonicteris aurantia (Pilbara) data not attaching correctly

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#4]
The listed species Rhinonicteris aurantia (Pilbara) has an unranked taxa created for it however data is still attaching to the nominate species (Rhinonicteris aurantia)

**Comment by charvolant** [comment]
`Rhinonicteris aurantia (Pilbara)` in a conservation list mixes a taxon with a particular status that only applies in a geographic area. It's impossible for a reasonable machine to split this out into name + geography and not name + author. There needs to be two things done:

* Have a geography column in conservation lists to restrict the localities for certain conservation listings
* Change the pipelines code to use geography as well as taxonID when conferring conservation status. https://github.com/gbif/pipelines/issues/884

**Comment by CamSlatyer** [comment]
Fixed in tactical taxonomy
