### ISSUE TITLE
Calyptorhynchus lathami lathami duplicates

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#41]
Duplicate entries occur for Calyptorhynchus lathami lathami on the taxonomic backbone which need to be synonymised

**Comment by charvolant** [comment]
20230329-1 index

Calyptorhynchus lathami lathami matches to https://biodiversity.org.au/afd/taxa/a7578d10-e7ae-48c2-9deb-bab619125a6c

Multiple instances correctly mapped onto AFD taxon

* https://biodiversity.org.au/afd/taxa/a7578d10-e7ae-48c2-9deb-bab619125a6c
  * ALA_DR656_391 https://lists.ala.org.au/speciesListItem/list/dr656?q=Calyptorhynchus+lathami+lathami
  * ALA_DR649_8 https://lists.ala.org.au/speciesListItem/list/dr649?q=Calyptorhynchus+lathami+lathami
  * ALA_DR652_147 https://lists.ala.org.au/speciesListItem/list/dr652?q=Calyptorhynchus+lathami+lathami

**Comment by CamSlatyer** [comment]
Correct in Tactical taxonomy
