### ISSUE TITLE
Duplicate entries of Calyptorhynchus lathami halmaturinus

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#42]
Duplicate entries of Calyptorhynchus lathami halmaturinus occur on taxonomic backbone and need to be synonymised

**Comment by charvolant** [comment]
20230329-1 index

Correectly matches to https://biodiversity.org.au/afd/taxa/3ea16688-8600-4d08-a362-1d5bd33af2aa

Additional names from conservation lists correctly mapped onto AFD instance

* https://biodiversity.org.au/afd/taxa/3ea16688-8600-4d08-a362-1d5bd33af2aa
  * ALA_DR656_390 https://lists.ala.org.au/speciesListItem/list/dr656?q=Calyptorhynchus+lathami+halmaturinus
  * ALA_DR653_186 https://lists.ala.org.au/speciesListItem/list/dr653?q=Calyptorhynchus+lathami+halmaturinus

**Comment by CamSlatyer** [comment]
Corrected in tactical taxonomy
