### ISSUE TITLE
Caladenia vulgaris var. nunguensis request to add to Tas Sensitive Species list

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#43]
Caladenia vulgaris var. nunguensis has been requested to be added to the Tas sensitive species list in ALA - but not recognised var by APNI / APC.  Recognised by Kew Gardens and is an Tas endemic. doesn't appear to have any records with the sub-specific name in ALA.  Need to clarify if accepted name and add to taxonomic backbone and Tas Sensitive Species list if it is.

Same as issue #95

**Comment by charvolant** [comment]
https://lists.ala.org.au/speciesListItem/list/dr491 currently has C. vulgaris as a supplied name and C. vulgaris var. nunguensis as an "ambiguous name" whatever that means.

@rosemaryjoconnor do you have any idea what is supposed to be correct?

Currently

* Caladenia vulgaris matches C. vulgaris
* Caladenia vulgaris var. nunguensis alone does not match
* Caladenia vulgaris var. nunguensis with genus and specific epithet matches C. vulgaris

**Comment by rosemaryjoconnor** [comment]
I don't have much of an idea as the list is directly downloaded from:
https://lists.ala.org.au/ws/speciesListItems/dr491?max=10000&includeKVP=true

**Comment by CamSlatyer** [comment]
Corrected
