### ISSUE TITLE
Bryobium irukandjianum is listed as a synonym of Eria irukandjiana

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#45]
Bryobium irukandjianum is listed as a synonym of Eria irukandjiana - should be the other way around i.e. Bryobium irukandjianum is the accepted name and Eria irukandjiana is a synonym according to APNI. Listed on QLD sensitive species list

**Comment by charvolant** [comment]
20230329-1 index

* Bryobium irukandjianum matches to accepted https://id.biodiversity.org.au/taxon/apni/51440902
* Eria irukandjiana is synonymised via https://id.biodiversity.org.au/instance/apni/51427382 to Bryobium irukandjianum

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
