### ISSUE TITLE
Anilios torresianus attributed to genus - should be attributed to Anilios polygrammicus

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#48]
Anilios torresianus attributed to genus - should be attributed to Anilios polygrammicus - QLD DES lists Anilios torresianus (north-eastern blind snake) with a synonym of Ramphotyphlops polygrammicus and Typhlops polygrammicus - AFD lists Typhlops polygrammicus as a synonym of Anilios polygrammicus

**Comment by charvolant** [comment]
20230329-1 index

* A. torresianus is accepted as https://biodiversity.org.au/afd/taxa/c68aa3bd-c67a-497e-bb0f-1d2c571d7f6c
* A. polygrammicus is excluded as https://biodiversity.org.au/afd/taxa/44d34161-b9b5-4e54-bc4f-f6cab3db2bb3

**Comment by Sherrin-ALA** [comment]
Anilios polygrammicus is Excluded (Misidentifications) of [TYPHLOPIDAE Merrem, 1820](https://biodiversity.org.au/afd/taxa/TYPHLOPIDAE) in AFD.

**Comment by Sherrin-ALA** [comment]
Cam to follow up with AFD

**Comment by CamSlatyer** [comment]
Now correct in system
