### ISSUE TITLE
Amytornis (Magnamytis) striatus whitei Mathews, 1910 incorrect in ALA

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#50]
according to AFD Amytornis (Magnamytis) striatus whitei Mathews, 1910 in ALA is incorrect (it doesn't exist) - should be Amytornis (Magnamytis) whitei Mathews, 1910 - correct and elevate to species level in backbone.  Listed on SA sensitive species list

**Comment by charvolant** [comment]
20230329-1 index

Amytornis striatus whitei is synonymised to A. whitei whitei https://biodiversity.org.au/afd/taxa/0ad00f36-f0e2-41b4-81b0-12f4b1211ad5 via https://biodiversity.org.au/afd/taxa/6938d696-70e3-4521-b49d-b9da91740fcb

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
