### ISSUE TITLE
Error in Synonomy in Corbicula

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#52]
Corbicula (Corbiculina) maroubra Iredale, 1943 is incorrectly shown in ALA as a valid taxon. It was synonomised with Corbicula (Corbicula) fluminea Müller, 1774 in 2016. This is a highly invasive species on biosecurity lists and needs to be corrected.

**Comment by CamSlatyer** [comment]
Thank you – sorry for being an idiot!

**Comment by TaniaGLaity** [comment]
Putting it down to teething problems and a huge sleep deficit!

**Comment by charvolant** [comment]
20230329-1 index

Corbicula maroubra matches https://biodiversity.org.au/afd/taxa/67d61422-5628-483a-8cc4-37f0b602e5df Corbicula (Corbicula) fluminea via  https://biodiversity.org.au/afd/taxa/a7b519c2-f77d-4409-ba55-a39d8f85c688

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
