### ISSUE TITLE
Multiple entries of Thalassarche eremita in taxonomic tree

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#55]
Thalassarche eremita has three entries in the taxonomic tree (with data attached to two). This needs to be reduced to one and the data matched to the correct taxon. Seems to be a product of bad name matching resulting in additional unranked taxa being added to the system as well as duplication of AFD and NZOR

**Comment by charvolant** [comment]
20230329-1 index

Thalassarche eremita  matches to NZOR-6-106266 

NZOR contains two entries for T. eremita

* NZOR-6-106266 http://data.nzor.org.nz/names/26444d39-66a3-4338-9a84-b70ddc32c559 without parent taxon
  * ALA_DR656_1806 https://lists.ala.org.au/speciesListItem/list/dr656?q=Thalassarche+eremita
  * ALA_DR18987_104 https://lists.ala.org.au/speciesListItem/list/dr18987?q=Thalassarche+eremita
  * ALA_DR654_713 https://lists.ala.org.au/speciesListItem/list/dr654?q=Thalassarche+eremita
  * https://biodiversity.org.au/afd/taxa/0cb5ead4-db11-4bc8-9ffb-67f0bc308fb9 excluded so the accepted NZOR reference takes precedence
* NZOR-6-111952 http://data.nzor.org.nz/names/0aa89b85-fa99-46ec-8e96-5681b176bd30

Consider penalising lower-rank entries without a parent taxon.

**Comment by charvolant** [comment]
See https://github.com/AtlasOfLivingAustralia/ala-name-matching/issues/195

**Comment by Sherrin-ALA** [comment]
NZOR Issue - regarded in Australia as a vagrant - even though listed we should not include to be consistent with AFD

**Comment by CamSlatyer** [comment]
Corrected in tactical taxonomy
