### ISSUE TITLE
Acanthiza (Acanthiza) pusilla magnirostris duplicated with Acanthiza pusilla archibaldi Mathews

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#57]
Acanthiza (Acanthiza) pusilla magnirostris Campbell, 1903 is the current valid name for the King Island Thornbill however ALA has both this and Acanthiza pusilla archibaldi Mathews, the name used in Tasmania. Acanthiza pusilla archibaldi Mathews needs to be treated as a junior synonym of  Acanthiza (Acanthiza) pusilla magnirostris Campbell, 1903 and the listing statuses consolidated under this name.

**Comment by charvolant** [comment]
20230329-1 index

* Acanthiza pusilla magnirostris matches accepted https://biodiversity.org.au/afd/taxa/fe7de157-e9c1-4672-be08-71b411847570
* Acanthiza pusilla archibaldi matches ALA_DR654_614 https://lists.ala.org.au/speciesListItem/list/dr654?q=Acanthiza+pusilla+archibaldi dr654 is the only source of A. p. archibaldi although AFD lists Acanthiza archibaldi as a synonym of A. p. magnirostris

We need some authority to synonymise the two.

**Comment by Sherrin-ALA** [comment]
Cam is following up with AFD.
Simon investigation issue around position of unranked taxa from conservation lists.

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
