### ISSUE TITLE
Multiple versions of Thalassarche bulleri platei Reichenow, 1898

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#58]
Thalassarche bulleri platei Reichenow, 1898 is the current valid name for Northern Buller's Albatross. The ALA has three combinations of the same species: Diomedea bulleri platei Reichenow, Thalassarche bulleri platei, and Thalassarche bulleri platei. These are a combination of unranked taxa and merging NZOR and AFD. They should be all combined into the correct name.

**Comment by charvolant** [comment]
20230329-1 index

Thalassarche bulleri platei matches accepted https://biodiversity.org.au/afd/taxa/c6d51093-2855-44d1-a72b-b612305c7bd3

All variants have been redirected to the AFD taxon

* https://biodiversity.org.au/afd/taxa/c6d51093-2855-44d1-a72b-b612305c7bd3
  * NZOR-6-20305 http://data.nzor.org.nz/names/ff9cd6d2-6127-4873-ae07-2510fd27532a
  * ALA_DR656_1802 https://lists.ala.org.au/speciesListItem/list/dr656?q=Thalassarche+bulleri+platei

**Comment by CamSlatyer** [comment]
Fixed in tactical taxonomy
