### ISSUE TITLE
Multiple versions of Tyto novaehollandiae castanops (Gould, 1837)

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#59]
Tyto novaehollandiae castanops (Gould, 1837) is the correct valid name for the Tasmanian subspecies of the masked owl. ALA has three combinations which should be combined.

**Comment by charvolant** [comment]
20230329-1 index

Tyto novaehollandiae castanops matched to accepted https://biodiversity.org.au/afd/taxa/2c30d58b-572b-4dab-8644-b222c28eb0ec

Variants allocated as

* https://biodiversity.org.au/afd/taxa/2c30d58b-572b-4dab-8644-b222c28eb0ec
  * ALA_DR654_721 https://lists.ala.org.au/speciesListItem/list/dr654?q=Tyto+novaehollandiae+castanops

**Comment by Sherrin-ALA** [comment]
Need to have family back in dr654 for the conservation list entry to be position correctly - unranked in current dev index.

**Comment by Sherrin-ALA** [comment]
Unclear why the EPBC conservation list (Tasmanian population) isn't matching to the name - needs investigation

**Comment by CamSlatyer** [comment]
Fixed in tactical taxonomy
