### ISSUE TITLE
Lindernia eremophiloides incorrectly showing as a synonym of Vandellia eremophiloides

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#6]
ALA incorrectly shows listed species L. eremophiloides as a synonym of Vandellia eremophiloides. Instead, Vandellia eremophiloides (W.R.Barker) Eb.Fisch., Schäferh. & Kai Müll. Is a synonym of Lindernia eremophiloides W.R.Barker (APC 2020)

**Comment by charvolant** [comment]
20230329-1 index

Lindernia eremophiloides is the accepted taxon and Vandellia eremophiloides the synonym https://id.biodiversity.org.au/taxon/apni/51438554

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
