### ISSUE TITLE
Calyptorhynchus latirostris incorrectly attached to family Cacatuidae instead of Zanda latrirostris

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#60]
Zanda latirostris Carnaby, 1948 is the correct valid name for Calyptorhynchus baudinii latirostris [Carnaby, I.C. 1948] and Calyptorhynchus latirostris. The ALA correctly has Zanda latirostris Carnaby, 1948 in the taxonomic tree at the correct point, however an unranked taxon has been inexplicably attached to Cacatuidae, which needs to be added (along with data and listing infomation) to Zanda Latirostris

**Comment by charvolant** [comment]
20230329-1

dr2201 contains several entries of the form Calyptorhynchus *epithet* and generates synthetic hider taxa. However, the output does not correctly supply parentNameUsageIDs or higher taxonomy for the synthetic taxa.

**Comment by charvolant** [comment]
See https://github.com/AtlasOfLivingAustralia/name-preprocessing/issues/7

**Comment by CamSlatyer** [comment]
Fixed in tactical taxonomy
