### ISSUE TITLE
Philomachus pugnax is a synonym of Calidris pugnax

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#61]
Calidris pugnax (Linnaeus, 1758) is the current accept name in Australia for Philomachus pugnax. ALA changed the name from Calidris to Philomachus last year but it has revereted. However major issue is that both taxa are in ALA taxonomy. The unranked Calidris pugnax should be merged with Philomachus pugnax and then both referred to Calidris pugnax (Linnaeus, 1758)

**Comment by charvolant** [comment]
20230329-2 index

* Philomachus pugnax matches NZOR-6-59078, accepted by NZOR, not present in AFD
* Calidris pugnax matches https://biodiversity.org.au/afd/taxa/177fbe63-4e52-4dd1-9f05-cf64ab8c48c8 accepted by AFD

This will require an ALA synonym.
*

**Comment by CamSlatyer** [comment]
Hi Doug

I disagree.

Both taxa are synonyms derived from Tringa pugnax (https://biodiversity.org.au/afd/taxa/Calidris_pugnax;Calidris)

In AFD, Tringa pugnax is regarded as a synonym of C. pugnax https://biodiversity.org.au/afd/taxa/Calidris_pugnax;Calidris

Philomachus pugnax IS in the AFD. Philomachus is regarded as a valid name https://biodiversity.org.au/afd/taxa/Philomachus . Philomachus pugnax (syn Tringa pugnax) is referred to Calidris pugnax. This is consistent with the principle international taxonomic names list for birds: https://birdsoftheworld.org/bow/species/ruff/cur/introduction

NZOR (and the EPBC Act) are both using outdated synonyms.

This is a classic example of disagreement between NZOR and AFD and it would be preferable not to worsen it.

Best wishes
Cam

**Comment by charvolant** [comment]
So to get this to fit as required, we'll need to introduce an overriding synonym to dr7933.

https://biodiversity.org.au/afd/search/names?search=true&keyword=Philomachus+pugnax turns up no results. The name does not appear in the current dump of AFD that we have. We do not have an authority that links Philomachus pugnax to either Tringa pugnax or Calidris pugnax.

**Comment by Sherrin-ALA** [comment]
This is the question about whether synonymising a genus means that all the species are automatically synonymised and whether the merge process should account for this.

**Comment by CamSlatyer** [comment]
Corrected in tactical taxonomy
