### ISSUE TITLE
Leucoptera (Lepidoptera) vs Leucoptera (Asteraceae)

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#63]
The moth genus Leucoptera currently has a description relating to a camomile daisy. This appears to be a recurrent problem linked to the name matching algorithm, which because it operates "bottom up" picks the closest first match without doing a reality check,

**Comment by charvolant** [comment]
This is probably not related to the name matching algorithm.

Descriptions on the BIE page come from the Encyclopedia of Life, via name lookup. The EoL API does not seem to respect supplied hints about class of phylum. A block list of weird results is maintained in the bie-hub configuration and Leucoptera has been added to that list.
