### ISSUE TITLE
Names matching does not handle botanical sections and series

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#64]
Botanical taxonomy uses informal classifications such as sections and series within complex genera like Eucalyptus and Dendrobium. Where section and series are included in the scientific name eg (sect: Monocalyptus) - it is causing errors in the names matching leading to the record being allocation to genus or family. The taxonomic framework in ALA includes sections and series, but does not treat them hierarchically, instead, adding them at species level without any grouping of species beneath them.

**Comment by charvolant** [comment]
Monocalyptus is not found in APNI https://biodiversity.org.au/nsl/services/search/names?product=APNI&tree.id=&name=Monocalyptus&inc._scientific=&inc.scientific=on&inc._cultivar=&inc._other=&max=100&display=apni&search=true 

Is there a specific example we can use to test?

**Comment by CamSlatyer** [comment]
Have removed pointless taxonomic levels (aka ones without parent child relationships) from flora in tactical taxonomy
