### ISSUE TITLE
Ptilotus exaltatus incorrectly displaying as Ptilotus nobilis

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#66]
Ptilotus exaltatus Nees was confirmed as the preferred APC name in July 2021, splitting it from P. nobilis. ALA received a complaint 7 June and the data team advised that it would be fixed with the then imminent data load. ALA still incorrectly shows P. nobilis as the preferred name.

**Comment by charvolant** [comment]
20230329-2 index

* Ptilotus exaltatus matches https://biodiversity.org.au/nsl/services/rest/taxon/apni/51430680
* P. nobilis matches https://id.biodiversity.org.au/taxon/apni/51430713 - misapplication to P. exaltatus ignored because there is an accepted taxon with that name

**Comment by CamSlatyer** [comment]
Corrected in Tactical taxonomy
