### ISSUE TITLE
ALA showing Bossiaea ornata (Lindl.) Benth as the preferred name for Bossiaea lalagoides F.Muell

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#67]
Bossiaea lalagoides was reerected from B. ornata in 2019. APNI shows both species as accepted, though APC lists B. ornata as the APC approved senior synonym. ALA shows the APC decision, not the most recent published name (2019) from Percy-Bower, J.M. & Parker, C.M. (28 March 2019), Updates to Western Australia’s vascular plant census for 2018. Nuytsia 30: 8

**Comment by charvolant** [comment]
20230329-2 index

* Bossiaea lalagoides matches https://id.biodiversity.org.au/taxon/apni/51702970 as an accepted name
* Bossiaea ornata matches https://id.biodiversity.org.au/taxon/apni/51702959 as an accepted name
* There now seems to be no synonymy between the two

**Comment by CamSlatyer** [comment]
Corrected in tactical taxonomy
