### ISSUE TITLE
Lindernia macrosiphonia incorrectly showing as a synonym of Vandella eremophiloides

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#7]
ALA incorrectly shows the listed species Lindernia macrosiphonia (F.Muell.) W.R.Barker as a synonym of Vandellia macrosiphonia (F.Muell.) Eb.Fisch., Schäferh. & Kai Müll. According to APC 2021, Lindernia macrosiphonia (F.Muell.) W.R.Barker is the accepted species.

**Comment by charvolant** [comment]
20230329-1 index

Lindernia macrosiphonia is now an accepted species https://id.biodiversity.org.au/taxon/apni/51438578

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
