### ISSUE TITLE
Threatened species missing from ALA Dielsiodoxa altimontana

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#79]
Described in 2022 by WA herbarium

**Comment by charvolant** [comment]
20230329-2 index

* Dielsiodoxa altimontana matches https://id.biodiversity.org.au/name/apni/51694038 (APNI only)

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
