### ISSUE TITLE
Lomandra acicularis incorrectly referred by ALA to Lomandra sp. Kimberley (M.D.Barrett 1036) WA Herbarium

### ISSUE THREAD

**Issue by TaniaGLaity** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#8]
ALA incorrectly refers listed species Lomandra acicularis ms M.D.Barrett to Lomandra sp. Kimberley (M.D.Barrett 1036) WA Herbarium and also has a separate entry for Lomandra acicularis M.D.Barrett. Lomandra acicularis M.D.Barrett is the correct current accepted name (APC 2021) and both Lomandra acicularis ms M.D.Barrett and Lomandra sp. Kimberley (M.D.Barrett 1036) WA Herbarium are junior synonyms

**Comment by charvolant** [comment]
20230329-1 index

All roads now lead to Lomandra acicularis

* "Lomandra acicularis" https://id.biodiversity.org.au/taxon/apni/51439083
* "Lomandra acicularis M.D.Barrett MS" https://id.biodiversity.org.au/instance/apni/51439077 accepted https://id.biodiversity.org.au/taxon/apni/51439083
* "Lomandra acicularis ms M.D.Barrett" https://id.biodiversity.org.au/instance/apni/51439077 accepted https://id.biodiversity.org.au/taxon/apni/51439083
* "Lomandra sp. Kimberley (M.D.Barrett 1036)" https://id.biodiversity.org.au/instance/apni/51439078 accepted https://id.biodiversity.org.au/taxon/apni/51439083

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
