### ISSUE TITLE
Phrase name species missing from ALA - listed species Eragrostis sp. Lake Carey (J. Paterson & J. Warden WB 40825) PN

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#82]
Listed phrase species missing from ALA Eragrostis sp. Lake Carey (J. Paterson & J. Warden WB 40825) PN

**Comment by charvolant** [comment]
20230329-1 index

Unable to find any variation of `Eragrostis.*Lake Carey` in any current source, or in APNI. Do we have a link in a list somewhere?

**Comment by Sherrin-ALA** [comment]
Something to be added to the ALA Species list

**Comment by CamSlatyer** [comment]
Duplication corrected in new taxonomy
