### ISSUE TITLE
Missing listed species described 2021 - Eucalyptus efflorescens

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#84]
Eucalyptus efflorescens was described 2021 -Eucalyptus efflorescens D.Nicolle & M.E.French
Flowery Mallee; Swainsona 35:120-122, Fig. 32 (2021). Threatened species - should be in ALA

Post tactical taxonomy same as issue #95

**Comment by Sherrin-ALA** [comment]
Added to Taxonomy via APNI.

**Comment by CamSlatyer** [comment]
In ALA but null value as well https://bie-dev.test.ala.org.au/species/ALA_Eucalyptus_efflorescens

**Comment by CamSlatyer** [comment]
Showing null issue

**Comment by CamSlatyer** [comment]
Now fixed
