### ISSUE TITLE
Missing threatened species (2021 described) Eucalyptus merleae

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#85]
Eucalyptus merleae was described in 2021 and is a threatened species - should be in ALA Eucalyptus merleae McQuoid & M.E.French Nuytsia 32:153-157, Fig. 2 (2021)

**Comment by charvolant** [comment]
20230329-1 index

* Eucalyptus merleae matched to https://id.biodiversity.org.au/name/apni/51631057 (APNI only)

**Comment by CamSlatyer** [comment]
In ALA but also null https://bie-dev.test.ala.org.au/search?q=Eucalyptus+merleae

**Comment by CamSlatyer** [comment]
Showing null issue

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
