### ISSUE TITLE
Spelling error Glycine lactivirens/lactovirens

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#88]
The ALA has Glycine lactivirens Tindale and Craven incorrectly listed as Glycine lactovirens Tindale & Craven

**Comment by charvolant** [comment]
20230329-1 index

* Glycine lactivirens  matches to https://id.biodiversity.org.au/node/apni/2910461
* Glycine lactovirens matches to https://id.biodiversity.org.au/name/apni/51417635 This is in APNI but not in APC and, while the taxonomic note indicates that it is an orthographic variant, it has not been synonymised to G. lactivirens

Suggest adding an overriding synonym to dr7933

**Comment by Sherrin-ALA** [comment]
Cam to follow up with APC/APNI

**Comment by CamSlatyer** [comment]
Correct in tactical taxonomy
