### ISSUE TITLE
Missing listed new species Gomphrena axillaris

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#89]
Gomphrena axillaris was described in 2021 - Gomphrena axillaris R.W.Davis & J.Palmer Swainsona 35:63-64, Fig. 2 (2021)

Post tactical taxonomy same as #95

**Comment by charvolant** [comment]
20230329-1 index

* Gomphrena axillaris matches https://id.biodiversity.org.au/name/apni/51421947 (APNI only)

**Comment by CamSlatyer** [comment]
Correctly showing in new taxonomy but Nulll issue is presenting

**Comment by CamSlatyer** [comment]
Now fixed
