### ISSUE TITLE
Missing phrase name listed species Goodenia sp. Charnley River (M.D. Barrett MDB 5163)

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#90]
WA listed species not in ALA Goodenia sp. Charnley River (M.D. Barrett MDB 5163)

**Comment by charvolant** [comment]
20230329-1 index

* Goodenia sp. Charnley River (M.D. Barrett MDB 5163) matches https://id.biodiversity.org.au/name/apni/51680167 (APNI only)

**Comment by CamSlatyer** [comment]
In new taxonomy, Null issue presenting
