### ISSUE TITLE
Missing phrase name listed species Hibiscus sp. Kununurra (K.F. Kenneally 1940) PN

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#91]
Hibiscus sp. Kununurra (K.F. Kenneally 1940) PN is a phrase name species listed in WA

**Comment by charvolant** [comment]
20230329-1 index

* Hibiscus sp. Kununurra (K.F. Kenneally 1940) matches https://id.biodiversity.org.au/name/apni/51680176 (APNI only)

**Comment by CamSlatyer** [comment]
In taxonomy - null issue presenting
