### ISSUE TITLE
New species missing from ALA (listed species) Hypocalymma inopinatum, Hypocalymma polyandrum

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#92]
Hypocalymma inopinatum, Hypocalymma polyandrum were described in 2022 Nuytsia 33:240-243 (2022) - listed species in WA

Post Tactical Taxonomy same as issue #95

**Comment by charvolant** [comment]
20230329-1 index

* Hypocalymma inopinatum matches https://id.biodiversity.org.au/name/apni/51694142 (APNI only)
* Hypocalymma polyandrum matches https://id.biodiversity.org.au/name/apni/51694161 (APNI only)

**Comment by CamSlatyer** [comment]
Now fixed
