### ISSUE TITLE
New (2021) listed species missing from ALA Indigofera rivularis, Indigofera rotula

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#93]
Indigofera rivularis, Indigofera rotula were described in WA and are listed species - Telopea 24:315-316 (2021)

See issue #95 post Tactical taxonomy - same issue

**Comment by charvolant** [comment]
20230329-1 index

* Indigofera rivularis matches https://id.biodiversity.org.au/name/apni/51418227 (APNI only)
* Indigofera rotula mathes https://id.biodiversity.org.au/name/apni/51418232 (APNI only)

**Comment by CamSlatyer** [comment]
Species in taxonomy, null issue presents

**Comment by CamSlatyer** [comment]
Now fixed
