### ISSUE TITLE
Phrase name species (listed) missing - Lambertia orbifolia subsp. Bowelling (A. Webb AW 09107) PN

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#94]
Lambertia orbifolia subsp. Bowelling (A. Webb AW 09107) PN is a missing listed phrase name species in WA

**Comment by charvolant** [comment]
20230329-1 index

* `Lambertia orbifolia.*Bowelling` not found in any of the currents sources. Which list includes this name?

**Comment by Sherrin-ALA** [comment]
Cam to followup with APNI

**Comment by CamSlatyer** [comment]
Now corrected in Tactical taxonomy
