### ISSUE TITLE
New taxon incorrectly referred to wrong genus Lemphoria humistrata

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#95]
Lemphoria humistrata was described in 2022 in WA - Lemphoria humistrata (F.Muell.) Al-Shehbaz & Lysak
Phytotaxa 549(2):239 (2022). ALA tries to refer species to Arabidella based on specific epithet

Post tactical taxonomy, this species was added successfully from both conservation list and APC. Unfortunately, since the conservation list was created, Lemphoria has been referred to Cuphonotus humistratus. This means the Lemphoria from the conservation list has not been picked up in the refinement process.

**Comment by Sherrin-ALA** [comment]
In development taxonomy from APNI

**Comment by CamSlatyer** [comment]
Now fixed
