### ISSUE TITLE
New listed species missing from ALA - Nicotiana salina

### ISSUE THREAD

**Issue by CamSlatyer** [AtlasOfLivingAustralia/Taxonomic-Issues-Register_new#99]
Nicotiana salina described 2022 - Nicotiana salina M.W.Chase, M.F.Fay & Christenh. Bot.Mag. (Kew Mag.) 38:422-424, Pl. 1000, Figs 2-3 (2021)

**Comment by charvolant** [comment]
20230329-1 index

* Nicotiana salina matches https://id.biodiversity.org.au/name/apni/51421363 (APNI only)

**Comment by CamSlatyer** [comment]
In new taxonomy but null issue presents

**Comment by CamSlatyer** [comment]
Correct in Tactical Taxonomy
